stages:
  - deploy

deploy:
  image: alpine/helm
  stage: deploy
  before_script:
    - apk add git openssh make bash
  script:
    - helm list -A
    - export NAMESPACE=$CI_DEFAULT_BRANCH
    - bash make.sh install
  only:
    - staging-1-3
    - ci
